### Create purchase

POST {{baseUrl}}/api/v1/purchases
Content-Type: application/json

{
  "description": "Test chair",
  "transactionDate": "2024-05-10",
  "amountUsd": 129.99
}

### Convert purchase
GET {{baseUrl}}/api/v1/purchases/{{id}}?currency=EUR


### Create Purchase
POST http://localhost:8443/api/v1/purchases
Content-Type: application/json

{
  "description": "Office Chair",
  "transactionDate": "2024-03-15",
  "amountUsd": 150.75
}


### Get Treasury Currency Descriptions
GET https://localhost:8443/api/v1/treasury/currency-descriptions


### Convert Purchase
GET https://localhost:8443/api/v1/purchases/a39a9a53-f141-4d78-ae42-c80b0924d87c?country_currency_desc=Austria-Euro
