### Create purchase

POST {{baseUrl}}/api/v1/purchases
Content-Type: application/json

{
  "description": "Test chair",
  "transactionDate": "2024-05-10",
  "amountUsd": 129.99
}

### Get Treasury Currency Descriptions
GET https://localhost:8080/api/v1/treasury/currency-descriptions


### Convert Purchase
GET https://localhost:8080/api/v1/purchases/58df4cf0-68b4-4993-8a98-92c98c2dc093?country_currency_desc=Brazil-Real
